#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""Check an upstream checkout's UI text against the localization's baseline.

    check-upstream-text.py --src <upstream-tree> [--json] [--quiet]
    check-upstream-text.py --src <upstream-tree> --write-baseline <file>

The menu's text lives in a handful of literals in src/frontend/sdl/ -- the
labels and notes of the settings rows, the values of their choices and the
strings draw_text is called with. This script reads those files out of a
pristine upstream tree (one no patch has been applied to), reduces them to the
strings a player could see, and compares that set with the baseline recorded
for the pinned commit.

    unchanged      build and package
    added          upstream new text the localization does not cover yet
                   (exit 3: translate it into 0007, then rerun)
    removed/changed upstream rewrote something that existed (exit 3 too --
                   the patch's context moved and the table may name a string
                   that is no longer drawn)

A formatted literal such as "%d %s" or a stray "abcdefghijklmnopqrstuvwxyz"
is not screen text and lands in the "other" set, which is reported but does
not decide the exit code. Keeping the two apart is what makes the output
readable when upstream has touched something unrelated.

The scanner is deliberately dumb and stable: it is versioned, and the version
is recorded beside the fingerprint, so a future change to the rules shows up
as a fingerprint change with a reason rather than as a mystery.
"""
import argparse
import hashlib
import json
import os
import re
import sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LOCK = os.path.join(REPO_ROOT, "standalone", "upstream.lock.json")
PATCH = os.path.join(REPO_ROOT, "standalone", "patches",
                     "0007-zh-menu-and-ui-language.patch")

SCANNER = 1

# The files the UI text lives in. 0007 edits these two (and adds i18n.h, which
# carries no text); the translation table is generated, and gen_tr.py is the
# tool, so neither of them is an upstream source of strings.
FILES = ["src/frontend/sdl/menu.cpp", "src/frontend/sdl/settings.cpp"]

LITERAL = re.compile(r'"((?:[^"\\]|\\.)*)"')
CJK = re.compile(r"[　-鿿＀-￯]")

EXIT_OK = 0
EXIT_TEXT_MOVED = 3


def classify(s):
    """ui / other -- whether a literal is plausibly something drawn on screen."""
    if CJK.search(s):
        return "ui"
    if len(s) >= 2 and s.isupper():
        return "ui"
    if len(s) >= 3 and " " in s:
        return "ui"
    return "other"


def collect(src_root, files):
    """Return {file: [(line_number, string), ...]} for the files that exist."""
    out = {}
    for rel in files:
        path = os.path.join(src_root, rel)
        if not os.path.isfile(path):
            continue
        with open(path, encoding="utf-8", errors="replace") as f:
            for i, line in enumerate(f, 1):
                for s in LITERAL.findall(line):
                    if not s:
                        continue
                    out.setdefault(rel, []).append((i, s))
    return out


def by_kind(entries, kind):
    """The distinct strings of one class."""
    return {s for rel in entries for _, s in entries[rel]
            if classify(s) == kind}


def fingerprint(entries):
    """sha256 over the distinct (file, string) pairs.

    Deliberately without the line numbers: this is the number the lock records,
    and it has to stay put when upstream shuffles its lines around. Line
    numbers live in the baseline file, where they tell a reader where a string
    came from.
    """
    h = hashlib.sha256()
    for rel in sorted(entries):
        for s in sorted({s for _, s in entries[rel]}):
            h.update(rel.encode("utf-8"))
            h.update(b"\0")
            h.update(s.encode("utf-8"))
            h.update(b"\0")
    return h.hexdigest()


def write_baseline(path, entries):
    rows = []
    for rel, pairs in sorted(entries.items()):
        for line, s in pairs:
            rows.append((rel, line, classify(s), s))
    rows.sort(key=lambda r: (r[0], r[2], r[3]))
    with open(path, "w", encoding="utf-8") as f:
        f.write("# generated by standalone/check-upstream-text.py, scanner %d\n" % SCANNER)
        f.write("# file:line\tclass\tstring\n")
        for rel, line, kind, s in rows:
            f.write("%s:%d\t%s\t%s\n" % (rel, line, kind, s))
    return len(rows)


def read_baseline(path):
    """Return (entries, scanner_version) or (None, None)."""
    if not os.path.isfile(path):
        return None, None
    entries = {}
    scanner = None
    with open(path, encoding="utf-8") as f:
        for raw in f:
            if raw.startswith("#"):
                m = re.search(r"scanner (\d+)", raw)
                if m:
                    scanner = int(m.group(1))
                continue
            if not raw.strip():
                continue
            head, kind, s = raw.rstrip("\n").split("\t")
            rel, line = head.rsplit(":", 1)
            entries.setdefault(rel, []).append((int(line), s))
    if scanner != SCANNER:
        return None, scanner
    return entries, scanner


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--src", default=None,
                    help="a pristine upstream tree (no patches applied)")
    ap.add_argument("--baseline",
                    default=os.path.join(REPO_ROOT, "standalone",
                                         "localization.baseline.tsv"),
                    help="baseline to compare against (default: %(default)s)")
    ap.add_argument("--write-baseline", metavar="FILE", default=None,
                    help="record the given tree as the new baseline and exit")
    ap.add_argument("--fingerprint-of", metavar="DIR", default=None,
                    help="print a tree's fingerprint and exit")
    ap.add_argument("--files", nargs="*", default=FILES,
                    help="which upstream files to scan")
    ap.add_argument("--json", action="store_true", help="machine-readable output")
    ap.add_argument("--quiet", action="store_true", help="only the verdict line")
    args = ap.parse_args()

    if not args.src and not args.fingerprint_of:
        ap.error("--src is required (or use --fingerprint-of alone)")

    if args.fingerprint_of:
        print(fingerprint(collect(args.fingerprint_of, args.files)))
        return EXIT_OK

    if args.write_baseline:
        entries = collect(args.src, args.files)
        n = write_baseline(args.write_baseline, entries)
        fp = fingerprint(entries)
        print("wrote %s: %d entries, fingerprint %s" % (args.write_baseline, n, fp))
        return EXIT_OK

    entries = collect(args.src, args.files)
    if not entries:
        sys.stderr.write("check-upstream-text: no UI text found under %s\n" % args.src)
        return 5
    here_fp = fingerprint(entries)
    here_ui = by_kind(entries, "ui")
    here_other = by_kind(entries, "other")

    base_entries, scanner = read_baseline(args.baseline)
    if base_entries is None:
        sys.stderr.write(
            "check-upstream-text: no usable baseline at %s\n"
            "  Record the pinned tree first:\n"
            "    git archive %s | tar -x -C build/pinned\n"
            "    python3 standalone/check-upstream-text.py --src build/pinned "
            "--write-baseline standalone/localization.baseline.tsv\n"
            % (args.baseline, json.load(open(LOCK, encoding="utf-8"))["core"]["source_commit"])
        )
        return 5

    base_ui = by_kind(base_entries, "ui")
    base_other = by_kind(base_entries, "other")

    added = sorted(here_ui - base_ui)
    removed = sorted(base_ui - here_ui)
    other_added = sorted(here_other - base_other)

    if args.json:
        print(json.dumps({
            "scanner": SCANNER,
            "baseline": args.baseline,
            "baseline_scanner": scanner,
            "fingerprint": here_fp,
            "counts": {"ui": len(here_ui), "other": len(here_other)},
            "added_ui": added,
            "removed_ui": removed,
            "added_other": other_added,
            "verdict": "unchanged" if not added and not removed else "moved",
        }, indent=2, ensure_ascii=False))
        return EXIT_OK if not added and not removed else EXIT_TEXT_MOVED

    if not args.quiet:
        print("check-upstream-text: %d UI strings, %d other literals"
              % (len(here_ui), len(here_other)))
        print("  fingerprint %s" % here_fp)

    if not added and not removed:
        if not args.quiet:
            print("  matches the baseline: no new upstream text to translate")
        return EXIT_OK

    print()
    if added:
        print("  %d string(s) upstream added that the localization does not cover:"
              % len(added))
        for s in added:
            print("    + %s" % s)
    if removed:
        print("  %d string(s) upstream no longer has (the table may still name "
              "one of these):" % len(removed))
        for s in removed:
            print("    - %s" % s)
    if other_added and not args.quiet:
        print("  %d non-UI literal(s) also appeared:" % len(other_added))
        for s in other_added[:20]:
            print("    ~ %s" % s)
        if len(other_added) > 20:
            print("    ... and %d more" % (len(other_added) - 20))
    print()
    print("  Translate the added strings into 0007, then rerun the pack script.")
    return EXIT_TEXT_MOVED


if __name__ == "__main__":
    raise SystemExit(main())
